// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: job-engine-events.proto

package job_engine_events

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobEngineEvents_NotifyJobFinished_FullMethodName = "/solarwinds.jobengine.protos.JobEngineEvents/NotifyJobFinished"
	JobEngineEvents_NotifyJobProgress_FullMethodName = "/solarwinds.jobengine.protos.JobEngineEvents/NotifyJobProgress"
)

// JobEngineEventsClient is the client API for JobEngineEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Migration of JobSchedulerEvents from orion\src\libs\src\SolarWinds.JobEngine\SolarWinds.JobEngine.Contract\IJobSchedulerEvents.cs
type JobEngineEventsClient interface {
	NotifyJobFinished(ctx context.Context, in *NotifyJobFinishedRequest, opts ...grpc.CallOption) (*NotifyJobFinishedResponse, error)
	NotifyJobProgress(ctx context.Context, in *NotifyJobProgressRequest, opts ...grpc.CallOption) (*NotifyJobProgressResponse, error)
}

type jobEngineEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewJobEngineEventsClient(cc grpc.ClientConnInterface) JobEngineEventsClient {
	return &jobEngineEventsClient{cc}
}

func (c *jobEngineEventsClient) NotifyJobFinished(ctx context.Context, in *NotifyJobFinishedRequest, opts ...grpc.CallOption) (*NotifyJobFinishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyJobFinishedResponse)
	err := c.cc.Invoke(ctx, JobEngineEvents_NotifyJobFinished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineEventsClient) NotifyJobProgress(ctx context.Context, in *NotifyJobProgressRequest, opts ...grpc.CallOption) (*NotifyJobProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyJobProgressResponse)
	err := c.cc.Invoke(ctx, JobEngineEvents_NotifyJobProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobEngineEventsServer is the server API for JobEngineEvents service.
// All implementations must embed UnimplementedJobEngineEventsServer
// for forward compatibility.
//
// Migration of JobSchedulerEvents from orion\src\libs\src\SolarWinds.JobEngine\SolarWinds.JobEngine.Contract\IJobSchedulerEvents.cs
type JobEngineEventsServer interface {
	NotifyJobFinished(context.Context, *NotifyJobFinishedRequest) (*NotifyJobFinishedResponse, error)
	NotifyJobProgress(context.Context, *NotifyJobProgressRequest) (*NotifyJobProgressResponse, error)
	mustEmbedUnimplementedJobEngineEventsServer()
}

// UnimplementedJobEngineEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobEngineEventsServer struct{}

func (UnimplementedJobEngineEventsServer) NotifyJobFinished(context.Context, *NotifyJobFinishedRequest) (*NotifyJobFinishedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyJobFinished not implemented")
}
func (UnimplementedJobEngineEventsServer) NotifyJobProgress(context.Context, *NotifyJobProgressRequest) (*NotifyJobProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyJobProgress not implemented")
}
func (UnimplementedJobEngineEventsServer) mustEmbedUnimplementedJobEngineEventsServer() {}
func (UnimplementedJobEngineEventsServer) testEmbeddedByValue()                         {}

// UnsafeJobEngineEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobEngineEventsServer will
// result in compilation errors.
type UnsafeJobEngineEventsServer interface {
	mustEmbedUnimplementedJobEngineEventsServer()
}

func RegisterJobEngineEventsServer(s grpc.ServiceRegistrar, srv JobEngineEventsServer) {
	// If the following call pancis, it indicates UnimplementedJobEngineEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobEngineEvents_ServiceDesc, srv)
}

func _JobEngineEvents_NotifyJobFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyJobFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineEventsServer).NotifyJobFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngineEvents_NotifyJobFinished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineEventsServer).NotifyJobFinished(ctx, req.(*NotifyJobFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngineEvents_NotifyJobProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyJobProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineEventsServer).NotifyJobProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngineEvents_NotifyJobProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineEventsServer).NotifyJobProgress(ctx, req.(*NotifyJobProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobEngineEvents_ServiceDesc is the grpc.ServiceDesc for JobEngineEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobEngineEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solarwinds.jobengine.protos.JobEngineEvents",
	HandlerType: (*JobEngineEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyJobFinished",
			Handler:    _JobEngineEvents_NotifyJobFinished_Handler,
		},
		{
			MethodName: "NotifyJobProgress",
			Handler:    _JobEngineEvents_NotifyJobProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job-engine-events.proto",
}
