// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: job-engine-service.proto

package job_engine_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobEngine_AddJob_FullMethodName                    = "/solarwinds.jobengine.protos.JobEngine/AddJob"
	JobEngine_UpdateJob_FullMethodName                 = "/solarwinds.jobengine.protos.JobEngine/UpdateJob"
	JobEngine_RemoveJob_FullMethodName                 = "/solarwinds.jobengine.protos.JobEngine/RemoveJob"
	JobEngine_RemoveJobs_FullMethodName                = "/solarwinds.jobengine.protos.JobEngine/RemoveJobs"
	JobEngine_CancelJob_FullMethodName                 = "/solarwinds.jobengine.protos.JobEngine/CancelJob"
	JobEngine_EnumerateScheduledJobs_FullMethodName    = "/solarwinds.jobengine.protos.JobEngine/EnumerateScheduledJobs"
	JobEngine_GetJobResultStream_FullMethodName        = "/solarwinds.jobengine.protos.JobEngine/GetJobResultStream"
	JobEngine_DeleteJobResult_FullMethodName           = "/solarwinds.jobengine.protos.JobEngine/DeleteJobResult"
	JobEngine_Clear_FullMethodName                     = "/solarwinds.jobengine.protos.JobEngine/Clear"
	JobEngine_GetPublicKey_FullMethodName              = "/solarwinds.jobengine.protos.JobEngine/GetPublicKey"
	JobEngine_AddExecutionEngine_FullMethodName        = "/solarwinds.jobengine.protos.JobEngine/AddExecutionEngine"
	JobEngine_RemoveExecutionEngine_FullMethodName     = "/solarwinds.jobengine.protos.JobEngine/RemoveExecutionEngine"
	JobEngine_SuspendExecutionEngine_FullMethodName    = "/solarwinds.jobengine.protos.JobEngine/SuspendExecutionEngine"
	JobEngine_ResumeExecutionEngine_FullMethodName     = "/solarwinds.jobengine.protos.JobEngine/ResumeExecutionEngine"
	JobEngine_EnumerateExecutionEngines_FullMethodName = "/solarwinds.jobengine.protos.JobEngine/EnumerateExecutionEngines"
	JobEngine_ExecutionEngineExists_FullMethodName     = "/solarwinds.jobengine.protos.JobEngine/ExecutionEngineExists"
	JobEngine_AddPolicy_FullMethodName                 = "/solarwinds.jobengine.protos.JobEngine/AddPolicy"
	JobEngine_UpdatePolicy_FullMethodName              = "/solarwinds.jobengine.protos.JobEngine/UpdatePolicy"
	JobEngine_RemovePolicy_FullMethodName              = "/solarwinds.jobengine.protos.JobEngine/RemovePolicy"
	JobEngine_EnumeratePolicies_FullMethodName         = "/solarwinds.jobengine.protos.JobEngine/EnumeratePolicies"
	JobEngine_PolicyExists_FullMethodName              = "/solarwinds.jobengine.protos.JobEngine/PolicyExists"
)

// JobEngineClient is the client API for JobEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Migration of IJobScheduler from orion/src/libs/src/SolarWinds.JobEngine/SolarWinds.JobEngine.Contract
// [TODO] We can refactor this single service to multiple services later. There are 3 visible areas Jobs, execution engines and policies.
// Also with our approach of executing jobs on JE, some rpc methods might be removed or adjusted.
type JobEngineClient interface {
	AddJob(ctx context.Context, in *ScheduledJob, opts ...grpc.CallOption) (*UuidType, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveJob(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveJobs(ctx context.Context, in *RemoveJobsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelJob(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnumerateScheduledJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumerateScheduledJobsResponse, error)
	GetJobResultStream(ctx context.Context, in *GetJobResultStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobResult], error)
	DeleteJobResult(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	AddExecutionEngine(ctx context.Context, in *AddExecutionEngineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SuspendExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnumerateExecutionEngines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumerateExecutionEnginesResponse, error)
	ExecutionEngineExists(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*ExistsResponse, error)
	AddPolicy(ctx context.Context, in *XmlElementType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdatePolicy(ctx context.Context, in *XmlElementType, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemovePolicy(ctx context.Context, in *PolicyIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnumeratePolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumeratePoliciesResponse, error)
	PolicyExists(ctx context.Context, in *PolicyIdRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
}

type jobEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewJobEngineClient(cc grpc.ClientConnInterface) JobEngineClient {
	return &jobEngineClient{cc}
}

func (c *jobEngineClient) AddJob(ctx context.Context, in *ScheduledJob, opts ...grpc.CallOption) (*UuidType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UuidType)
	err := c.cc.Invoke(ctx, JobEngine_AddJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) RemoveJob(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_RemoveJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) RemoveJobs(ctx context.Context, in *RemoveJobsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_RemoveJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) CancelJob(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) EnumerateScheduledJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumerateScheduledJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumerateScheduledJobsResponse)
	err := c.cc.Invoke(ctx, JobEngine_EnumerateScheduledJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) GetJobResultStream(ctx context.Context, in *GetJobResultStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobEngine_ServiceDesc.Streams[0], JobEngine_GetJobResultStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetJobResultStreamRequest, JobResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobEngine_GetJobResultStreamClient = grpc.ServerStreamingClient[JobResult]

func (c *jobEngineClient) DeleteJobResult(ctx context.Context, in *UuidType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_DeleteJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) GetPublicKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, JobEngine_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) AddExecutionEngine(ctx context.Context, in *AddExecutionEngineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_AddExecutionEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) RemoveExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_RemoveExecutionEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) SuspendExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_SuspendExecutionEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) ResumeExecutionEngine(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_ResumeExecutionEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) EnumerateExecutionEngines(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumerateExecutionEnginesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumerateExecutionEnginesResponse)
	err := c.cc.Invoke(ctx, JobEngine_EnumerateExecutionEngines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) ExecutionEngineExists(ctx context.Context, in *UriType, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, JobEngine_ExecutionEngineExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) AddPolicy(ctx context.Context, in *XmlElementType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_AddPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) UpdatePolicy(ctx context.Context, in *XmlElementType, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) RemovePolicy(ctx context.Context, in *PolicyIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobEngine_RemovePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) EnumeratePolicies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EnumeratePoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumeratePoliciesResponse)
	err := c.cc.Invoke(ctx, JobEngine_EnumeratePolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobEngineClient) PolicyExists(ctx context.Context, in *PolicyIdRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, JobEngine_PolicyExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobEngineServer is the server API for JobEngine service.
// All implementations must embed UnimplementedJobEngineServer
// for forward compatibility.
//
// Migration of IJobScheduler from orion/src/libs/src/SolarWinds.JobEngine/SolarWinds.JobEngine.Contract
// [TODO] We can refactor this single service to multiple services later. There are 3 visible areas Jobs, execution engines and policies.
// Also with our approach of executing jobs on JE, some rpc methods might be removed or adjusted.
type JobEngineServer interface {
	AddJob(context.Context, *ScheduledJob) (*UuidType, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*emptypb.Empty, error)
	RemoveJob(context.Context, *UuidType) (*emptypb.Empty, error)
	RemoveJobs(context.Context, *RemoveJobsRequest) (*emptypb.Empty, error)
	CancelJob(context.Context, *UuidType) (*emptypb.Empty, error)
	EnumerateScheduledJobs(context.Context, *emptypb.Empty) (*EnumerateScheduledJobsResponse, error)
	GetJobResultStream(*GetJobResultStreamRequest, grpc.ServerStreamingServer[JobResult]) error
	DeleteJobResult(context.Context, *UuidType) (*emptypb.Empty, error)
	Clear(context.Context, *ClearRequest) (*emptypb.Empty, error)
	GetPublicKey(context.Context, *emptypb.Empty) (*GetPublicKeyResponse, error)
	AddExecutionEngine(context.Context, *AddExecutionEngineRequest) (*emptypb.Empty, error)
	RemoveExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error)
	SuspendExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error)
	ResumeExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error)
	EnumerateExecutionEngines(context.Context, *emptypb.Empty) (*EnumerateExecutionEnginesResponse, error)
	ExecutionEngineExists(context.Context, *UriType) (*ExistsResponse, error)
	AddPolicy(context.Context, *XmlElementType) (*emptypb.Empty, error)
	UpdatePolicy(context.Context, *XmlElementType) (*emptypb.Empty, error)
	RemovePolicy(context.Context, *PolicyIdRequest) (*emptypb.Empty, error)
	EnumeratePolicies(context.Context, *emptypb.Empty) (*EnumeratePoliciesResponse, error)
	PolicyExists(context.Context, *PolicyIdRequest) (*ExistsResponse, error)
	mustEmbedUnimplementedJobEngineServer()
}

// UnimplementedJobEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobEngineServer struct{}

func (UnimplementedJobEngineServer) AddJob(context.Context, *ScheduledJob) (*UuidType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJob not implemented")
}
func (UnimplementedJobEngineServer) UpdateJob(context.Context, *UpdateJobRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedJobEngineServer) RemoveJob(context.Context, *UuidType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveJob not implemented")
}
func (UnimplementedJobEngineServer) RemoveJobs(context.Context, *RemoveJobsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveJobs not implemented")
}
func (UnimplementedJobEngineServer) CancelJob(context.Context, *UuidType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedJobEngineServer) EnumerateScheduledJobs(context.Context, *emptypb.Empty) (*EnumerateScheduledJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumerateScheduledJobs not implemented")
}
func (UnimplementedJobEngineServer) GetJobResultStream(*GetJobResultStreamRequest, grpc.ServerStreamingServer[JobResult]) error {
	return status.Errorf(codes.Unimplemented, "method GetJobResultStream not implemented")
}
func (UnimplementedJobEngineServer) DeleteJobResult(context.Context, *UuidType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJobResult not implemented")
}
func (UnimplementedJobEngineServer) Clear(context.Context, *ClearRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedJobEngineServer) GetPublicKey(context.Context, *emptypb.Empty) (*GetPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedJobEngineServer) AddExecutionEngine(context.Context, *AddExecutionEngineRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExecutionEngine not implemented")
}
func (UnimplementedJobEngineServer) RemoveExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExecutionEngine not implemented")
}
func (UnimplementedJobEngineServer) SuspendExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendExecutionEngine not implemented")
}
func (UnimplementedJobEngineServer) ResumeExecutionEngine(context.Context, *UriType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeExecutionEngine not implemented")
}
func (UnimplementedJobEngineServer) EnumerateExecutionEngines(context.Context, *emptypb.Empty) (*EnumerateExecutionEnginesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumerateExecutionEngines not implemented")
}
func (UnimplementedJobEngineServer) ExecutionEngineExists(context.Context, *UriType) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutionEngineExists not implemented")
}
func (UnimplementedJobEngineServer) AddPolicy(context.Context, *XmlElementType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPolicy not implemented")
}
func (UnimplementedJobEngineServer) UpdatePolicy(context.Context, *XmlElementType) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedJobEngineServer) RemovePolicy(context.Context, *PolicyIdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePolicy not implemented")
}
func (UnimplementedJobEngineServer) EnumeratePolicies(context.Context, *emptypb.Empty) (*EnumeratePoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumeratePolicies not implemented")
}
func (UnimplementedJobEngineServer) PolicyExists(context.Context, *PolicyIdRequest) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PolicyExists not implemented")
}
func (UnimplementedJobEngineServer) mustEmbedUnimplementedJobEngineServer() {}
func (UnimplementedJobEngineServer) testEmbeddedByValue()                   {}

// UnsafeJobEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobEngineServer will
// result in compilation errors.
type UnsafeJobEngineServer interface {
	mustEmbedUnimplementedJobEngineServer()
}

func RegisterJobEngineServer(s grpc.ServiceRegistrar, srv JobEngineServer) {
	// If the following call pancis, it indicates UnimplementedJobEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobEngine_ServiceDesc, srv)
}

func _JobEngine_AddJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduledJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).AddJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_AddJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).AddJob(ctx, req.(*ScheduledJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_RemoveJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).RemoveJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_RemoveJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).RemoveJob(ctx, req.(*UuidType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_RemoveJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).RemoveJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_RemoveJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).RemoveJobs(ctx, req.(*RemoveJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).CancelJob(ctx, req.(*UuidType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_EnumerateScheduledJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).EnumerateScheduledJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_EnumerateScheduledJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).EnumerateScheduledJobs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_GetJobResultStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetJobResultStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobEngineServer).GetJobResultStream(m, &grpc.GenericServerStream[GetJobResultStreamRequest, JobResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobEngine_GetJobResultStreamServer = grpc.ServerStreamingServer[JobResult]

func _JobEngine_DeleteJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).DeleteJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_DeleteJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).DeleteJobResult(ctx, req.(*UuidType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).GetPublicKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_AddExecutionEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExecutionEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).AddExecutionEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_AddExecutionEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).AddExecutionEngine(ctx, req.(*AddExecutionEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_RemoveExecutionEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UriType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).RemoveExecutionEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_RemoveExecutionEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).RemoveExecutionEngine(ctx, req.(*UriType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_SuspendExecutionEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UriType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).SuspendExecutionEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_SuspendExecutionEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).SuspendExecutionEngine(ctx, req.(*UriType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_ResumeExecutionEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UriType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).ResumeExecutionEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_ResumeExecutionEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).ResumeExecutionEngine(ctx, req.(*UriType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_EnumerateExecutionEngines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).EnumerateExecutionEngines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_EnumerateExecutionEngines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).EnumerateExecutionEngines(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_ExecutionEngineExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UriType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).ExecutionEngineExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_ExecutionEngineExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).ExecutionEngineExists(ctx, req.(*UriType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_AddPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XmlElementType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).AddPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_AddPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).AddPolicy(ctx, req.(*XmlElementType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XmlElementType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).UpdatePolicy(ctx, req.(*XmlElementType))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_RemovePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).RemovePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_RemovePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).RemovePolicy(ctx, req.(*PolicyIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_EnumeratePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).EnumeratePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_EnumeratePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).EnumeratePolicies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobEngine_PolicyExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEngineServer).PolicyExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEngine_PolicyExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEngineServer).PolicyExists(ctx, req.(*PolicyIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobEngine_ServiceDesc is the grpc.ServiceDesc for JobEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solarwinds.jobengine.protos.JobEngine",
	HandlerType: (*JobEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddJob",
			Handler:    _JobEngine_AddJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobEngine_UpdateJob_Handler,
		},
		{
			MethodName: "RemoveJob",
			Handler:    _JobEngine_RemoveJob_Handler,
		},
		{
			MethodName: "RemoveJobs",
			Handler:    _JobEngine_RemoveJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _JobEngine_CancelJob_Handler,
		},
		{
			MethodName: "EnumerateScheduledJobs",
			Handler:    _JobEngine_EnumerateScheduledJobs_Handler,
		},
		{
			MethodName: "DeleteJobResult",
			Handler:    _JobEngine_DeleteJobResult_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _JobEngine_Clear_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _JobEngine_GetPublicKey_Handler,
		},
		{
			MethodName: "AddExecutionEngine",
			Handler:    _JobEngine_AddExecutionEngine_Handler,
		},
		{
			MethodName: "RemoveExecutionEngine",
			Handler:    _JobEngine_RemoveExecutionEngine_Handler,
		},
		{
			MethodName: "SuspendExecutionEngine",
			Handler:    _JobEngine_SuspendExecutionEngine_Handler,
		},
		{
			MethodName: "ResumeExecutionEngine",
			Handler:    _JobEngine_ResumeExecutionEngine_Handler,
		},
		{
			MethodName: "EnumerateExecutionEngines",
			Handler:    _JobEngine_EnumerateExecutionEngines_Handler,
		},
		{
			MethodName: "ExecutionEngineExists",
			Handler:    _JobEngine_ExecutionEngineExists_Handler,
		},
		{
			MethodName: "AddPolicy",
			Handler:    _JobEngine_AddPolicy_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _JobEngine_UpdatePolicy_Handler,
		},
		{
			MethodName: "RemovePolicy",
			Handler:    _JobEngine_RemovePolicy_Handler,
		},
		{
			MethodName: "EnumeratePolicies",
			Handler:    _JobEngine_EnumeratePolicies_Handler,
		},
		{
			MethodName: "PolicyExists",
			Handler:    _JobEngine_PolicyExists_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobResultStream",
			Handler:       _JobEngine_GetJobResultStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job-engine-service.proto",
}
